name: README Info Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: GitHub README Generator
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "en"
          TIMEZONE: "Asia/Kolkata"
          SHOW_LINES_OF_CODE: "True"
          COMMIT_BY_ME: "True"
          COMMIT_MESSAGE: "Update README"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_DAILY_COMMIT: "True"
          SHOW_WEEKLY_COMMIT: "True"
          SHOW_LANGUAGE: "True"
          SHOW_TOTAL_CONTRIBUTIONS: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_UPDATED_DATE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LOC_CHART: "False"
